language: python
python:
  - "3.4"
env:
  global:
    secure: "TaEIU4Must++rLSsB3eRe0vtPPsHhuDFIyUIRLp8P/c8Tq1isrzxeTfWeWU1sa5WVYsMXy8Q6JqgBYpopml3B0OtOcO7T10YSvrzcgIQOoSoInsRwr7ernSLFWDORDLPCW6BdRfVmTqFjGuGK9qor5J6LUMrAs4KQ+wthH1m8Wc="
before_install:
  - sudo apt-add-repository -y "deb http://archive.ubuntu.com/ubuntu trusty main universe"
  - sudo apt-get -qq -y update
  - sudo apt-get install -y iverilog
  - pip install --src ./src -e git+https://github.com/m-labs/migen.git@master#egg=migen
  - mkdir vpi
  - iverilog-vpi --name=vpi/migensim src/migen/vpi/main.c src/migen/vpi/ipc.c
  - ./.travis/get-xilinx.sh
script:
  - PYTHONPATH=. python3 testbench/escape.py
  - python3 make.py
notifications:
  email: false
  irc:
    channels:
      - chat.freenode.net#nist-ionstorage
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d26782523952bfa53814
